language: c
compiler: gcc
sudo: required
addons:
  apt:
    packages:
    - rake
    - bison git gperf
    - git
    - gperf
    - binutils-mingw-w64-i686
    - binutils-mingw-w64-x86-64
    - gcc-mingw-w64-i686
    - gcc-mingw-w64-x86-64
    - gcc-mingw-w64
    - mingw-w64
before_script:
  - PREFIX=x86_64-w64-mingw32
  - CC=$PREFIX-gcc
  - CXX=$PREFIX-g++
  - CPP=$PREFIX-cpp
  - RANLIB=$PREFIX-ranlib
  - PATH="/usr/x86_64-w64-mingw32/bin:$PATH"
exec "$@"
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-gwi/.travis_build_config.rb build_config.rb
script:
  - make all test
