language: c
compiler:
  - mingw-w64
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison git gperf
    - sudo apt-get install binutils-mingw-w64-i686 binutils-mingw-w64-x86-64
    - sudo apt-get install gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 gcc-mingw-w64 mingw-w64
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-gwi/.travis_build_config.rb build_config.rb
script:
  - make all test
